# Generated by Django 4.2.5 on 2024-02-10 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0004_alter_place_description_long"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={
                "ordering": ["order"],
                "verbose_name": "Изображение",
                "verbose_name_plural": "Изображения",
            },
        ),
        migrations.AlterModelOptions(
            name="place",
            options={"verbose_name": "Локация", "verbose_name_plural": "Локации"},
        ),
        migrations.RenameField(
            model_name="place",
            old_name="description_long",
            new_name="long_description",
        ),
        migrations.RemoveField(
            model_name="image",
            name="image_order",
        ),
        migrations.RemoveField(
            model_name="place",
            name="description_short",
        ),
        migrations.RemoveField(
            model_name="place",
            name="title_short",
        ),
        migrations.AddField(
            model_name="image",
            name="order",
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="place",
            name="short_description",
            field=models.TextField(blank=True, verbose_name="Краткое описание"),
        ),
        migrations.AlterField(
            model_name="image",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="places.place",
                verbose_name="Место",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="placeID",
            field=models.SlugField(
                blank=True, default="", max_length=100, verbose_name="ID места"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="title",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="Название места"
            ),
        ),
    ]
